version = 1

[*]
; add global presets here
parallel = 1
cache-ram = 32768
flash-attn = on
n-gpu-layers = 99
jinja = true
ub = 1024
b = 1024
threads = 8
mmproj-offload = false

[Qwen3.6-bartowski-27B-MTP-Q4_K_M]
load-on-startup = true
alias = Qwen3.6-27B,qwen3.6
model = /models/Qwen3.6-bartowski-27B-MTP-Q4_K_M.gguf
ctx-size = 65536
#ctx-size = 120000
#hf =  bartowski/Qwen_Qwen3.6-27B-GGUF:Q4_K_M
temp = 0.6
top-p = 0.8
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
spec-draft-n-max=2
spec-type=draft-mtp,ngram-mod
cache-type-k=q8_0
cache-type-v=q8_0

[gemma-4-31B-it-qat-UD-Q4_K_XL]
alias = gemma4-31B
model = /models/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
temp = 1
top-p = 0.95
top-k = 64
presence-penalty = 0.0
repeat-penalty = 1.0
ctx-size = 32768
spec-draft-n-max=2
spec-type=draft-mtp,ngram-mod
cache-type-k=q8_0
cache-type-v=q8_0
model-draft = /models/mtp-gemma-4-31B-it.gguf
